//restrictions specific to each
const lifestyles = {
  halal: [
    "pork",
    "wine",
    "alcohol",
    "gelatin",
    "whey",
    "bacon",
    "glycerol",
    "glycerin",
    "glyceride",
    "pepsin",
    "rennet",
    "beer batters",
    "carmine color",
    "cochineal",
    "cytidene",
    "disodium guanosine 5'",
    "disodium uridine 5′",
    "erythritol",
    "ethanol",
    "fermented cider",
    "ham",
    "hard cider",
    "inosito 5′",
    "l-cysteine",
    "lard",
    "nucleotides",
    "rum",
    "sherry wine",
    "sovent extracted modified lecithin",
    "soya sauce",
    "surimi",
    "wine vinegar",
    "animal shortening",
    "brewer's yeast extract",
    "collagen",
    "diglyceride",
    "ethyl alcohol",
    "kosher gelatin",
    "hydrolized animal protein",
    "monoglycerides",
    "phospolipids",
    "sausage",
    "animal shortening",
    "lipase",
  ],
  kosher: [
    "Shellfish",
    "Shrimp",
    "Prawns",
    "Lobster",
    "Scallops",
    "Mussels",
    "Oysters",
    "Squid",
    "Octopus",
    "Crabs",
    "caviar",
    "margarine",
    "grape juice",
    "wines",
    "alcohol",
    "vinegar",
    "cheese",
    "albumin",
    "animal fat",
    "lard",
    "liquor",
    "lumpfish",
    "tartaric acid",
    "tartar",
    "algol",
    "glycerol",
    "glycerin",
    "monoglycerides",
    "diglycerides",
    "sucroglycerides",
    "gelatin",
  ],
  vegetarian: ["Egg", "Dairy", "Milk", "Cheese", "Honey"],
  vegan: [],
};

//list of all ingredients
const allRestrictions = [
  "Walnuts",
  "Lactose",
  "Peanuts",
  "Eggs",
  "Gluten",
  "Shellfish",
  "Shrimp",
  "Prawn",
  "Squid",
  "Crab",
  "Lobster",
  "Soy",
  "Wheat",
  "Peanuts",
  "Cashews",
  "Almonds",
  "Hazelnuts",
  "Tree Nuts",
  "Lupin",
  "Land snails",
  "Celery",
  "Leaves",
  "Seeds",
  "Stalks",
  "Sesame",
  "Lecithin",
  "Soy milk",
  "Citrus",
  "Fish",
  "Milk",
];

export { lifestyles, allRestrictions };
